apiVersion: gitops.jenkins-x.io/v1alpha1
kind: SourceConfig
metadata:
  creationTimestamp: null
spec:
  groups:
  - owner: caiqi1111
    provider: https://github.com
    providerKind: github
    repositories:
    - name: caiqitest
    - name: newtest
    - name: test1
    - name: test2
    - name: test3
    - name: velaux
    scheduler: in-repo
  slack:
    channel: '#jenkins-x-pipelines'
    kind: failureOrNextSuccess
    pipeline: release
